### ISSUE TITLE
Question: Using checksum to avoid download

### ISSUE THREAD

**Issue by tisba** [hashicorp/go-getter#126]
Hi!

I was wondering if it is possible (or even in scope of go-getter) to skip a download in case a checksum is provided and a file at the destination can be found that matches this checksum.

My use case would be, that I have to download rather large files and I'd like to avoid the redundant downloads. Of corse I can check the destination myself, but like I said, I was wondering if this is considered to be in-scope for this package.

**Comment by apparentlymart** [comment]
Hi @tisba,

I think if there's a "natural" way to detect that the destination directory already contains the content from the remote server (without storing any go-getter specific extra metadata) then that is within the scope of a getter. We can see this in the "git" getter, for example, where if the destination directory is already a git repository then it will fetch updates into that existing directory rather than starting with an entirely new clone.

Likewise I think it could be reasonable for a particular getter to somehow produce a checksum of the destination directory/file and see if it matches the checksum on the server, if the protocol in question offers a standard way to do this. `go-getter`'s mission is to interact with existing standards and de-facto standards rather than invent its own, and so I think in practice there aren't many protocols where this would be possible without inventing some `go-getter`-specific conventions, which I expect we would rather not do.

One scenario I could imagine doing this is for the S3 getter when the target is a single file (rather than a directory): the getter could in principle calculate the MD5 hash of the destination file and optimize away the full download if the response from S3 happens to have that hash as the `ETag`. The ETag isn't _always_ the MD5 hash (e.g. if the object was uploaded in several chunks), but if it were not then it would just fall back to re-downloading the whole file again, so not a problem. Whether the additional complexity is worth it just for S3 in particular is not clear to me, but if the implementation of this were simple then perhaps it would be okay.

Skimming over the other getters, I think all of the existing possibilities for optimization have already been taken: the VCS ones use VCS features to fetch a delta when possible, and the local file backend will prefer to create a symlink if possible to avoid copying the source.

If you're talking about the `checksum` argument that some of the getters interpret, that is intended for verifying the given retrieved is what's expected rather than optimizing away a fetch. To optimize away a fetch I think the getter would need to use evidence already on disk at the destination directory/file to make the decision, rather than the `checksum` argument.

**Comment by azr** [comment]
Howdy, this was done this in #125.

It only works for single file downloads and is something packer was doing already, so I needed to implement it in order to use the go-getter in packer.

**Comment by tisba** [comment]
Wow, that's great, thanks @azr!
