### ISSUE TITLE
The scp-like URL test fails after Go 1.12.8.

### ISSUE THREAD

**Issue by 178inaba** [hashicorp/go-getter#203]
```console
$ go1.12.8 test -run TestGitDetector
--- FAIL: TestGitDetector (0.00s)
    --- FAIL: TestGitDetector/git::ssh://git@github.xyz.com:org/project.git (0.00s)
        detect_git_test.go:67: unexpected error: invalid source string: git::ssh://git@github.xyz.com:org/project.git
FAIL
exit status 1
FAIL	github.com/hashicorp/go-getter	0.109s
```

`net/url` has been fixed so it is no longer possible to use non-numeric strings after the colon.
https://github.com/golang/go/commit/3226f2d492963d361af9dfc6714ef141ba606713

**Comment by apparentlymart** [comment]
We had intentionally blocked this sort of thing in earlier changes anyway in order to resolve the ambiguity between scp-like forms where a colon introduces the path and URL-like forms where it introduces a port.

The current intended behavior is that the `ssh://` URL prefix is _not_ valid to use with the scp-like form... you either use the scp form (no prefix) or the URL form, not a mixture of the two.

So, I think the work here will be to rationalize our own ruleset with the new check in `net/url` and see if we can recover our own specialized error message that was intended to help the user switch to one of the two valid forms, rather than the hybrid. It should still be an error, but ideally with better error text.
