### ISSUE TITLE
Travis CI at pull request fails with GCS authentication

### ISSUE THREAD

**Issue by 178inaba** [hashicorp/go-getter#210]
For example, the following job has failed.
https://travis-ci.org/hashicorp/go-getter/jobs/584188625
https://travis-ci.org/hashicorp/go-getter/jobs/584194575

I tried it in a local environment, but this seems to be caused by a failure of GCS authentication.

I think that you should specify the service account json key file in `GOOGLE_APPLICATION_CREDENTIALS` as shown in the code below.
https://github.com/hashicorp/go-getter/blob/c712229b2c963d9d75ab8b12d6d2a06ac4f58407/get_gcs_test.go#L14-L23

Ref:
https://developers.google.com/accounts/docs/application-default-credentials

**Comment by azr** [comment]
Hello, if you check it out on master (currently https://github.com/hashicorp/go-getter/commit/c712229b2c963d9d75ab8b12d6d2a06ac4f58407) the build passes; it is because the credentials are private and therefore not set for non member PRs. I can think of two options:
* make credentials public again ( but then they are public ❗️ )
* skip these tests when credentials are not set

**Comment by 178inaba** [comment]
> skip these tests when credentials are not set

I think this is good.
The above method may be preferable considering the case where the developer tests locally.

If you do not select this, you must announce that `GOOGLE_APPLICATION_CREDENTIALS` is required when developing in the local environment.
